//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proekt.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> DataApp { get; set; }
        public Nullable<int> StatusOrderID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual User User { get; set; }
    }
}
