//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proekt.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSupplier
    {
        public int ID { get; set; }
        public Nullable<int> Productid { get; set; }
        public Nullable<int> ReceiptofproductID { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> PriceUnit { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ReceiptOfProduct ReceiptOfProduct { get; set; }
    }
}
