//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proekt.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Supply = new HashSet<Supply>();
            this.SupProdCountry = new HashSet<SupProdCountry>();
            this.ZvOrder = new HashSet<ZvOrder>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<decimal> Cast { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public byte[] Image1 { get; set; }
    
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply> Supply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupProdCountry> SupProdCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZvOrder> ZvOrder { get; set; }
    }
}
