//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proekt.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int ID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> DataSupp { get; set; }
        public Nullable<int> StatusSuppId { get; set; }
        public Nullable<int> SuppliersID { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Product Product { get; set; }
        public virtual StatusSupp StatusSupp { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
